# Generated by Django 5.2.12 on 2026-03-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starting_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valide", "valide"),
                            ("en attente", "attente"),
                            ("suppr", "suppr"),
                        ],
                        default="valide",
                        max_length=16,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "medication",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical.medication",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "starting_date"],
            },
        ),
    ]
