# Generated by Django 5.2.11 on 2026-02-04 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valide", "valide"),
                            ("suppr", "suppr"),
                            ("en_attente", "en_attente"),
                        ],
                        default="valide",
                        max_length=10,
                    ),
                ),
                ("begin_date", models.DateField()),
                ("end_date", models.DateField()),
                ("comment", models.CharField(blank=True, max_length=1000)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical.medication",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical.patient",
                    ),
                ),
            ],
        ),
    ]
