# Generated by Django 5.2.11 on 2026-02-19 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_period_start', models.DateField()),
                ('validity_period_end', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('on-hold', 'on-hold'), ('entered-in-error', 'entered-in-error')], default='active', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('authored_on', models.DateTimeField(auto_now_add=True)),
                ('medication_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_requests', to='medical.medication')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_requests', to='medical.patient')),
            ],
            options={
                'ordering': ['-authored_on', 'id'],
            },
        ),
    ]
