# Generated by Django 5.2.10 on 2026-01-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_start_date',
            field=models.DateField(),
        ),
    ]
